language: java
before_install:
- curl https://raw.github.com/liveSense/all/master/travis-settings.xml --create-dirs
  -o target/travis/settings.xml
jdk:
- openjdk6
script:
- mvn deploy --settings target/travis/settings.xml
env:
  global:
  - secure: NeNyv5i88uFIyxNi8bQtFRm171l/tyVHrz8oG4XI/uPftxak/Ve8DuOJ+nC3XUV+9Ht0kYy/BwmPNtWviNIRnz4PRBg6C9NavGguqWVUgIl7Me/gnA9xHUqOnLJOq+Dva41amfhPVXYwsEKkiO7zfyklRZ8ENGSE6QnB7IoCLjY=
  - secure: YbSuXa6d9YAzug/p5+MmafdMePaUWK2oqXOElHRSJ1C5Azkmrf8c6UFP+1QEc2sVg3NvXp3o4K30JAGbVc+dOJUNKaGRi/E1LXbGnOGejj2tgd0iEVfan9TJPOOqGh7EJn3gB7oS0JL5yUPdcTJ2qZ2hSdiTxHsDbvOMKGjKH68=
